services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - SCHEMA=public
    ports:
      - "5432:5432"
    volumes:
      - ./db_data_postgres:/var/lib/postgresql/data

volumes:
  db_data_postgres: